//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int ApplicationId { get; set; }
        public int JobId { get; set; }
        public int JobSeekerId { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string Status { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual JobPosting JobPosting { get; set; }
    }
}
