//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPosting()
        {
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int JobId { get; set; }
        public int EmployerId { get; set; }
        public int CategoryId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string JobType { get; set; }
        public string JobRole { get; set; }
        public string Location { get; set; }
        public Nullable<int> MinExperience { get; set; }
        public Nullable<int> MaxExperience { get; set; }
        public int Openings { get; set; }
        public string RequiredQualification { get; set; }
        public string SalaryRange { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string RequiredSkills { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        public virtual JobCategory JobCategory { get; set; }
    }
}
